# Generated by Django 4.2.7 on 2023-11-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_content', to='app.content'),
        ),
    ]
